### ISSUE TITLE
Error building classpath. Could not acquire write lock for 'artifact:org.bytedeco:mkl:2020.3-1.5.4'

### ISSUE THREAD

**Issue by Jimmysit0** [pmonks/gravity#1]
### Steps to Reproduce:
Clone the repo and then run clj -i init.clj -r

### Expected Result:
The program working 

### Actual Result:
Got an error, here's the log: 
Error building classpath. Could not acquire write lock for 'artifact:org.bytedeco:mkl:2020.3-1.5.4'
java.lang.IllegalStateException: Could not acquire write lock for 'artifact:org.bytedeco:mkl:2020.3-1.5.4'
	at org.eclipse.aether.internal.impl.synccontext.named.NamedLockFactoryAdapter$AdaptedLockSyncContext.acquire(NamedLockFactoryAdapter.java:146)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:209)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:264)
	at clojure.tools.deps.alpha.extensions.maven$get_artifact.invokeStatic(maven.clj:122)
	at clojure.tools.deps.alpha.extensions.maven$get_artifact.invoke(maven.clj:116)
	at clojure.tools.deps.alpha.extensions.maven$eval1092$fn__1094.invoke(maven.clj:137)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at clojure.tools.deps.alpha$download_libs$fn__816$fn__817.invoke(alpha.clj:462)
	at clojure.tools.deps.alpha.util.concurrent$submit_task$task__505.invoke(concurrent.clj:34)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at **java.base/java.lang.Thread.run(Thread.java:831)**

**Comment by pmonks** [comment]
That looks like a tools.deps issue, rather than anything to do with this project itself.  What happens when you run `clj -P` in the same directory?  What version of the Clojure CLI do you have installed (`clj --version`)?  What version of the JVM are you using (`java -version`)?  What OS are you on (`uname -a`, if not on Windows)?

**Comment by pmonks** [comment]
Closing due to lack of followup, and my inability to reproduce the issue.
